// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-GvrM9ewh8CsUlT8r_hzPOwwCPiOcMfI',
    appId: '1:945433978201:web:f96cd6e3099da78468d848',
    messagingSenderId: '945433978201',
    projectId: 'flutter-test-a00ff',
    authDomain: 'flutter-test-a00ff.firebaseapp.com',
    storageBucket: 'flutter-test-a00ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznZPXXdoL_T76rHWXOfLDQRkCNiOdzWg',
    appId: '1:945433978201:android:beac732cee46a08268d848',
    messagingSenderId: '945433978201',
    projectId: 'flutter-test-a00ff',
    storageBucket: 'flutter-test-a00ff.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2Lj1DqXQC5jXh-XllYLLJYz5LrRRa8Y',
    appId: '1:945433978201:ios:753416fa05344a9468d848',
    messagingSenderId: '945433978201',
    projectId: 'flutter-test-a00ff',
    storageBucket: 'flutter-test-a00ff.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2Lj1DqXQC5jXh-XllYLLJYz5LrRRa8Y',
    appId: '1:945433978201:ios:753416fa05344a9468d848',
    messagingSenderId: '945433978201',
    projectId: 'flutter-test-a00ff',
    storageBucket: 'flutter-test-a00ff.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}